# Generated by Django 4.2.6 on 2023-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_addprofit_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200, null=True)),
                ('replay', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='referraldetails',
            name='spot_percent_direct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referraldetails',
            name='spot_percent_level_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referraldetails',
            name='spot_percent_level_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referraldetails',
            name='spot_percent_level_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_plan',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
